###get the api end point
GET http://localhost:8000/

###fetch all the taasks api
GET http://localhost:8000/api/v1/task

###
POST http://localhost:8000/api/v1/task
Content-Type: application/json

{"task":"her","hr":1}

###
DELETE  http://localhost:8000/api/v1/task/625e081f1cd2b4518ea174af


###to make the request to user-api
GET http://localhost:8000/api/v1/user

###to make the post to the user
POST http://localhost:8000/api/v1/user
Content-Type: application/json
 
{"username":"didd",
"email":"paud@gmail.com",
"password":"asddf"}

###to delete the user
DELETE http://localhost:8000/api/v1/user/625e2cb76db323a09d677dea